package ru.stqa.jft.addressbook;// Generated by Selenium IDE

import org.junit.Test;

public class ContactCreationTests extends TestBase {

    @Test
    public void contactCreationTest() {
        initContactCreation();
        fillContactForm(new ContactData("Ed", "Testovich", "Testov",
                "+79811234567", "test@test.ru"));
        submitContactCreation();
    }
}
